In [43]:
import numpy as np
a = [5,2,3]
b = [1.5,2,-1]
T = np.ones((3, 3)) / 9

def pos(num,matrix):
    cnt = 0
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            cnt+=1
            if cnt==num:
                return (i,j)
alpha = 0.0001  
for iter in range(int(1e5)):
    for index in range(9):
        row,col = pos(index+1,t)
        t[row][col] = t[row][col]*(b[row]-a[col])**2
        diff = np.subtract.outer(b_values, a_values)
        T[row,col] = T[i, j] * np.exp(-alpha * diff[i, j]**2)

In [63]:
import numpy as np

# Values for X1 and X2
a_values = np.array([1, 2, 3])
b_values = np.array([1.5, 2, -1])

# Initialize the coupling matrix T
T = np.ones((3, 3)) / 9

# Set the learning rate
learning_rate = 0.001

# Iterate until convergence
iter = 0
while True:
    # Calculate the differences
    diff = np.subtract.outer(b_values, a_values)
    
    # Update each element of T
    for i in range(3):
        for j in range(3):
            T[i, j] = T[i, j] * np.exp(-learning_rate * diff[i, j]**2)
    
    # Normalize the rows and columns
    T = T / np.sum(T, axis=0)
    T = T / np.sum(T, axis=1)[:, np.newaxis]
    
    # Check for convergence
    # You can define a convergence criterion based on your requirements
    
    # Break the loop if convergence is reached
    iter +=1
    if iter==1e5:
        break

# Print the optimal coupling matrix
print("Optimal Coupling Matrix:")
print(T)

Optimal Coupling Matrix:
[[2.57866210e-003 9.97421338e-001 2.62040633e-041]
 [1.35992480e-049 1.41399314e-003 9.98586007e-001]
 [1.00000000e+000 2.75577189e-215 1.53160350e-322]]


In [64]:
np.sum(T,axis = 0)

array([1.00257866, 0.99883533, 0.99858601])

In [ ]:
https://www.youtube.com/watch?v=wObV_hwu2QM&ab_channel=DataWithMo